### ISSUE TITLE
[231021] QuizRecordDetailView 

### ISSUE THREAD

**Issue by MartinLeeSJ** [MartinLeeSJ/FlagQuiz#2]
## TODO
- QuizRecordDetailVC, View, VM  완성
## Detail
- [x] 퀴즈결과 점수의 등급 및, 점수, 퀴즈를 푼 일시 확인
- [x] 맞힌 퀴즈, 틀린 퀴즈, 미제출 퀴즈 확인
- [x] 해당 퀴즈 문항의 나라 상세 확인 (CountryDetailView 재활용)
